//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Booking_Lessons_For_Driving.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Card
    {
        public double IDNumber { get; set; }
        public string CVV { get; set; }
        public string CardOwner { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public double CardNumber { get; set; }
    }
}
