//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Booking_Lessons_For_Driving.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public string Session { get; set; }
        public System.DateTime Time { get; set; }
        public string Price { get; set; }
        public double IDNumber { get; set; }
        public double Total { get; set; }
    }
}
