//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_Booking_Lessons_For_Driving.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Learner
    {
        public double IDNumber { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public string CellNumber { get; set; }
        public string TestingCenter { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Province { get; set; }
        public string Status { get; set; }
    }
}
